development:
  adapter: postgresql
  encoding: unicode
  database: homes_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: homes_test
  pool: 5
  host: localhost
